app:
  integration:
    base-url: https://fgis.gost.ru/fundmetrology/cm/xcdb/vri/select
  xls-location: xlsx/allMI.xlsx
  reports:
    directory: ./reports
  parse:
    first-data-row: 3
  pagination:
    default-page-number: 0
    default-page-size: 20
  settings:
    max-arshin-results-count: 3
    request-delay-ms: 1000
spring:
  application:
    name: arshin-checkup
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/arshin_db?currentSchema=arshin_schema
    username: chernykh
    password: LoveAlmighty48!
    hikari:
      schema: arshin_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS arshin_schema
      connection-timeout: 10000
